image: humancellatlas/metrics-build-box

stages:
  - deploy

variables:
  ## variables for the build
  AWS_DEFAULT_REGION: us-east-1
  ## variables for docker
  # When using dind service we need to instruct docker, to talk with the
  # daemon started inside of the service. The daemon is available with
  # a network connection instead of the default /var/run/docker.sock socket.
  #
  # The 'docker' hostname is the alias of the service container as described at
  # https://docs.gitlab.com/ee/ci/docker/using_docker_images.html#accessing-the-services
  #
  # Note that if you're using Kubernetes executor, the variable should be set to
  # tcp://localhost:2375 because of how Kubernetes executor connects services
  # to the job container
  DOCKER_HOST: tcp://localhost:2375
  # When using dind, it's wise to use the overlayfs driver for
  # improved performance.
  DOCKER_DRIVER: overlay2

services:
- docker:dind

deploy:
  services:
   - docker:18.09-dind
  stage: deploy
  script:
    - which docker
    - pip install awscli --user --upgrade
    - make image
    - make push
  only:
    - f2f-hackatho-image-build
