version: '3'
services:
  api:
    build: .
    ports: 
      - "8080:8080"
    environment:
      - MONGO_URI=mongodb://db:27017/admin
      - RABBIT_HOST=mq
    links:
      - "mongo:db"
      - "rabbitmq:mq"
  mongo:
    image: mongo:3.4.3
    ports:
      - "27017:27017"
  rabbitmq:
    image: rabbitmq:3.7.7-alpine
    ports:
      - "5672:5672"
networks:
  default:
    

