version: '3'
services:
  api:
    build: .
    ports:
      - "8080:8080"
      - "9091:9091"
    environment:
      - MONGO_URI=mongodb://db:27017/admin
      - RABBIT_HOST=mq
      - JMX_PORT=9091
      - SCHEMA_BASE_URI=http://schema.dev.data.humancellatlas.org/
    links:
      - "mongo:db"
      - "rabbitmq:mq"
  mongo:
    image: mongo:3.4.3
    ports:
      - "27017:27017"
  rabbitmq:
    image: rabbitmq:3.7.7-management-alpine
    ports:
      - "5672:5672"
      - "15672:15672"
  broker:
    image: quay.io/humancellatlas/ingest-broker:master_dbd4096
    ports:
      - "5000:5000"
    environment:
      - INGEST_API=http://api:8080
    links:
      - "api:api"
  staging-manager:
    image: quay.io/humancellatlas/ingest-staging-manager:master_7c4c332
    environment:
      - INGEST_API=http://api:8080
      - RABBIT_URL=amqp://mq:5672
      - STAGING_API=http://upload:8080
      - INGEST_API_KEY=${INGEST_API_KEY}
    links:
      - "api:api"
      - "mongo:db"
      - "rabbitmq:mq"
      - "upload-service:upload"
  validator:
    image: quay.io/humancellatlas/ingest-validator:master
    environment:
      - INGEST_API=http://api:8080
      - RABBIT_URL=amqp://mq:5672
      - UPLOAD_API_URL=http://upload:8888
      - RABBITMQ_ACCESSION_QUEUE=ingest.metadata.accession.queue
      - RABBITMQ_VALIDATION_QUEUE=ingest.metadata.validation.queue
      - JSON_SCHEMA_VALIDATION=ACTIVE
      - OLS_VALIDATION=INACTIVE
      - FILE_VALIDATION=INACTIVE
      - ONTOLOGY_SCHEMA_BASE_URL=https://raw.githubusercontent.com/HumanCellAtlas/metadata-schema/4.6.1/json_schema/ontology_json
      - OLS_API_URL=http://upload:8080
      - UPLOAD_API_KEY=(redacted)
    links:
      - "api:api"
      - "rabbitmq:mq"
      - "upload-service:upload"
  upload-service:
    image: humancellatlas/mock-upload-service
    ports:
      - "8888:8080"
networks:
  default:
